export default {
    translation: {
      Login: {
        Title: "Logg inn for å fortsette",
        Username_or_Email: "Brukernavn eller e-postadresse",
        Password: "Passord",
        Login_Button: "Logg inn",
        Forgot_Password: "Glemt passord?",
        Username_or_Email_Desc: "Et brukernavn eller e-post må oppgis.",
        Account_Password_Desc: "Vennligst skriv inn passordet ditt.",
        Account_Incorrect: "Fant ingen brukerkonto som samsvarer med oppgitte opplysninger.",
        Many_Attempts: "Du har brukt for mange påloggingsforsøk. Prøv igjen senere.",
        Recaptcha_Error: "Kunne ikke validere reCAPTCHA-data.",
        Request_Failed: "Request failed with status code 404",
        CSRF_Token: "CSRF-tokenet stemmer ikke."
      },
      Reset_Password: {
        Password_Reset: "Be om tilbakestilling av passord",
        Email: "E-post",
        New_Password_Required: "Et nytt passord kreves.",
        Password_Characters_Min: "Det nye passordet ditt bør være på minst 8 tegn.",
        Password_Not_Match: "Passordene du skrev inn er forskjellige. Prøv på nytt.",
        Account_Email: "Skriv inn e-postadressen for kontoen din, for å motta instruksjoner om hvordan du tilbakestiller passordet ditt.",
        Valid_Email: "En gyldig e-postadresse må oppgis for å fortsette.",
        Send_Email: "Send E-post",
        Return_to_Login: "Gå tilbake til pålogging",
        Reset_Password: "Tilbakestill passord",
        New_Password: "Nytt passord",
        New_Password_Desc: "Passord må være på minst 8 tegn.",
        Confirm_New_Password: "Bekreft nytt passord",
        Send_Email_Link: "Vi har sendt lenken for tilbakestilling av passord på e-post!"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Enhetssjekkpunkt",
        Recovery_Code: "Gjenopprettingskode",
        Authentication_Code: "Autentiseringskode",
        Enter_Two_Factor_Desc_1: "Skriv inn to-faktor-tokenet generert av enheten din.",
        Enter_Two_Factor_Desc_2: "For å fortsette må du skrive inn en av gjenopprettingskodene som ble generert da du konfigurerte 2-faktor-autentisering for denne kontoen.",
        Lost_Device: "Jeg har mistet enheten min",
        Have_Device: "Jeg har enheten min",
        Continue: "Forsett"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "You must provide an authentication code to continue.",
        Two_Factor_Activate_Desc_2: "Two-factor authentication is currently enabled on your account.",
        Two_Factor_Activate_Desc_3: "Authenticator code must be 6 digits.",
        Two_Factor_Active_Title: "Two-factor authentication enabled",
        Two_Factor_Active_Desc_1: "Two-factor authentication has been enabled on your account. Should you lose access to your authenticator device, you'll need to use one of the codes displayed below in order to access your account.",
        Two_Factor_Active_Desc_2: "These codes will not be displayed again. ",
        Two_Factor_Active_Desc_3: "Please take note of them now by storing them in a secure repository such as a password manager.",
        Two_Factor_Active_Button: "Lukk",
        Two_Factor_Disabled_Desc: "You do not currently have two-factor authentication enabled on your account. Click the button below to begin configuring it.",
        Two_Factor_Disable_Desc_1: "You must provide your current password in order to continue.",
        Two_Factor_Disable_Desc_2: "In order to disable two-factor authentication you will need to provide your account password.",
        Two_Factor_Disable_Title: "Current Password",
        Two_Factor_Disable_Button: "Disable Two-Factor",
        Two_Factor_Setup_Desc_1: "Enter the code from your authenticator device after scanning the QR image.",
        Two_Factor_Setup_Desc_2: "Alternatively, enter the following token into your authenticator application:",
        Two_Factor_Setup_Button: "Setup",
        Two_Factor_Incorrect_Password: "The password provided was not valid.",
        Button_Disable: "Deaktivert",
        Button_Enable: "Aktivert",
        Create_Api_Desc_Title: "Beskrivelse",
        Create_Api_Desc: "A description of this API key.",
        Create_Api_Ips_Title: "Tillatte IP-er",
        Create_Api_Ips_Desc: "Leave blank to allow any IP address to use this API key, otherwise provide each IP address on a new line.",
        Create_Api_Button: "Opprett",
        Update_Email_Desc_1: "You must provide your current account password.",
        Update_Email_Required: "Email is a required field",
        Update_Email_Success_Title: "Success",
        Update_Email_Success: "Your primary email has been updated.",
        Update_Email_Error_Title: "Feil",
        Update_Email_Button: "Update E-post",
        Update_Password_Title: "Nytt passord",
        Update_Password_Desc_1: "You must provide your current password.",
        Update_Password_Desc_2: "Password confirmation does not match the password you entered.",
        Update_Password_Desc_3: "Your new password should be at least 8 characters in length and unique to this website.",
        Update_Password_Required: "Password is a required field",
        Update_Password_Button: "Update Password",
        Update_Password_Error: "The password provided was invalid for this account.",
        Update_Password_Min: "The password must be at least 8 characters",
        Confirm_Password: "Bekreft passord",
        Account_Page_Title: "Account Overview",
        Account_Two_Factor_Required_Title: "2-Factor Required",
        Account_Two_Factor_Required_Desc: "Your account must have two-factor authentication enabled in order to continue.",
        Account_Update_Email_Title: "Update Email Address",
        Account_Setup_Two_Factor_Title: "Configure Two Factor",
        Api_Page_Title: "Account API",
        Api_Create_Title: "Create API Key",
        Api_List_Title: "API Keys",
        Api_List_Loading: "Laster inn...",
        Api_List_Empty: "No API keys exist for this account.",
        Api_List_Used_1: "Last used: ",
        Api_List_Used_2: "Never",
        Api_Delete_Title: "Confirm key deletion",
        Api_Delete_Button: "Yes, delete key",
        Api_Delete_Desc: "Are you sure you wish to delete this API key? All requests using it will immediately be invalidated and will fail.",
        Api_Setup_Title: "Your API Key",
        Api_Setup_Desc: "The API key you have requested is shown below. Please store this in a safe location, it will not be shown again.",
        Api_Min_Characters: "Description must be at least 4 characters",
        Api_Setup_Button: "Lukk",
        Api_Ip_Incorrect_1: "IP address 1 must be a valid IP address.",
        Api_Ip_Incorrect_2: "IP address 2 must be a valid IP address.",
        Api_Ip_Incorrect_3: "IP address 3 must be a valid IP address."
      },
      Search: {
        Search_Title: "Search term",
        Search_Desc_1: "Please enter at least three characters to begin searching.",
        Search_Desc_2: "Enter a server name, uuid, or allocation to begin searching."
      },
      Dashboard: {
        Dash_Page_Title: "Kontrollpanel",
        Dash_Show_Server_1: "Viser andres servere",
        Dash_Show_Server_2: "Viser dine servere",
        Dash_Show_Server_3: "Det er ingen andre servere å vise.",
        Dash_Show_Server_4: "Det er ingen servere som er knyttet til kontoen din."
      },
      Server_Row: {
        Server_Unlimited: "Ubegrenset",
        Server_Suspended: "Suspendert",
        Server_Connect_Error: "Tilkoblingsfeil",
        Server_Transferring: "Overfører",
        Server_Installing: "Installing",
        Server_Restoring_Backup: "Gjenoppretter sikkerhetskopi",
        Server_Unavailable: "Utilgjengelig",
        Server_Of: "av"
      },
      Elements: {
        Elements_Cancel_Button: "Avbryt",
        Elements_Copy_Text: "Kopiert til utklippstavlen.",
        Elements_Error: "Det oppsto en feil under lasting av nettsiden. Prøv å oppdatere siden."
      },
      Server: {
        Server_Page_Title: "Konsoll",
        Server_Transfer_Console: "Overføring feilet.",
        Server_Archived_Console: "Serveren har blitt arkivert, prøver å koble til mål-noden..",
        Server_Send_Command: "Skriv inn en kommando...",
        Server_State_Console: "Serveren ",
        Server_State_Starting: "starter",
        Server_State_Offline: "er offline",
        Server_State_Stopping: "stopper",
        Server_State_Running: "kjører",
        Server_State_Connect: "Kobler til...",
        Server_State_Install: "Denne serveren kjører for øyeblikket installasjonsprosessen, og de fleste handlinger er utilgjengelige.",
        Server_State_Transfer: "Denne serveren blir for øyeblikket overført til en annen node, og alle handlinger er derfor utilgjengelige.",
        Server_Button_Start: "Start",
        Server_Button_Restart: "Restart",
        Server_Button_Kill: "Drep",
        Server_Button_Stop: "Stopp",
        Server_Memory_Graph_Title: "Minnebruk",
        Server_Cpu_Graph_Title: "CPU-bruk",
        Server_Graph_Desc: "Serveren er offline.",
        Server_Websocket_Error: "Det oppsto en feil under validering av legitimasjonen som ble oppgitt for websocket. Vennligst oppdater siden.",
        Server_Connect_Server: "Vi har problemer med å koble til serveren din. Vennligst vent..."
      },
      Server_Backup: {
        Backup_Page_Title: "Sikkerhetskopier",
        Backup_Empty_1: "Det ser ikke ut til at vi har flere sikkerhetskopier å vise deg, prøv å gå tilbake en side.",
        Backup_Empty_2: "Det ser ut til at det ikke er noen sikkerhetskopier lagret for denne serveren.",
        Backup_Forbidden: "Sikkerhetskopier kan ikke opprettes for denne serveren, fordi at sikkerhetskopieringsgrensen er satt til 0.",
        Backup_Information: "sikkerhetskopier er opprettet for denne serveren.",
        Backup_Create_Title_1: "Opprett en ny sikkerhetskopi",
        Backup_Create_Title_2: "Navn på sikkerhetskopi",
        Backup_Create_Title_3: "Ignorerte filer og mapper",
        Backup_Create_Title_4: "Låst",
        Backup_Create_Desc_1: "Hvis oppgitt, er dette navnet som skal brukes for å referere til denne sikkerhetskopien.",
        Backup_Create_Desc_2: "Enter the files or folders to ignore while generating this backup. Leave blank to use the contents of the .pteroignore file in the root of the server directory if present. Wildcard matching of files and folders is supported in addition to negating a rule by prefixing the path with an exclamation point.",
        Backup_Create_Desc_3: "Forhindrer at denne sikkerhetskopien slettes før den låses opp.",
        Backup_Create_Start_Button: "Start sikkerhetskopiering",
        Backup_Create_Button: "Opprett ny sikkerhetskopi",
        Backup_Created_Title: "Vil du låse opp denne sikkerhetskopien?",
        Backup_Created_Desc_1: "Er du sikker på at du vil låse opp denne sikkerhetskopien? Den vil ikke lenger være beskyttet mot automatiske eller utilsiktede slettinger.",
        Backup_Created_Button: "Ja, lås opp",
        Backup_Restore_Title: "Vil du gjenopprette denne sikkerhetskopien?",
        Backup_Restore_Desc_1: "Denne serveren vil bli stoppet, slik sikkerhetskopien kan gjenopprettes. Når sikkerhetskopieringen har startet, vil du ikke kunne kontrollere serverens skru serveren av og på, få tilgang til filbehandleren eller opprette flere sikkerhetskopier før den er fullført.",
        Backup_Restore_Desc_2: "Er du sikker på at du vil fortsette?",
        Backup_Restore_Desc_3: "Fjern alle filer og mapper før du gjenoppretter denne sikkerhetskopien.",
        Backup_Restore_Button: "Gjennopprett backup",
        Backup_Delete_Title: "Vil du slette denne sikkerhetskopien?",
        Backup_Delete_Desc_1: "Er du sikker på at du vil slette denne sikkerhetskopien? Dette er en permanent operasjon, og sikkerhetskopien kan ikke gjenopprettes når den er slettet.",
        Backup_Delete_Button: "Ja, slett Sikkerhetskopien",
        Backup_SubMenu_Download: "Last ned",
        Backup_SubMenu_Restore: "Gjennopprett",
        Backup_SubMenu_Unlock: "Lås opp",
        Backup_SubMenu_Lock: "Lås",
        Backup_SubMenu_Delete: "Slett"
      },
      Server_Databases: {
        Database_Page_Title: "Databaser",
        Database_Show_Empty: "Det ser ut til at du ikke har noen databaser.",
        Database_Show_Forbidden: "Databaser kan ikke opprettes for denne serveren.",
        Database_Limit_Desc: "databaser har blitt tildelt denne serveren.",
        Database_Create_Title_1: "Opprett ny database",
        Database_Create_Title_2: "Databasenavn",
        Database_Create_Title_3: "Tilkoblinger fra",
        Database_Create_Desc_1: "Et beskrivende navn for databaseforekomsten.",
        Database_Create_Desc_2: "Hvor tilkoblinger skal tillates fra. Bruk % for wildcards.",
        Database_Create_Button_1: "Opprett database",
        Database_Create_Button_2: "Ny database",
        Database_Create_Error_1: "Det oppsto en uventet feil under behandlingen av denne forespørselen. Prøv på nytt.",
        Database_Create_Error_2: "Et databasenavn må oppgis.",
        Database_Create_Error_3: "Databasenavnet må være på minst 3 tegn.",
        Database_Create_Error_4: "Databasenavnet må ikke overstige 48 tegn.",
        Database_Create_Error_5: "Databasenavn skal bare inneholde alfanumeriske tegn, understreker, bindestreker og/eller punktum.",
        Database_Create_Error_6: "En tilkoblingsverdi må oppgis.",
        Database_Create_Error_7: "En gyldig tilkoblingsadresse må oppgis.",
        Database_Delete_Title_1: "Bekreft sletting av database",
        Database_Delete_Title_2: "Bekreft databasenavn",
        Database_Delete_Title_3: "Detaljer for databasetilkobling",
        Database_Delete_Title_4: "Endepunkt",
        Database_Delete_Title_5: "Tilkoblinger fra",
        Database_Delete_Title_6: "Brukernavn",
        Database_Delete_Title_7: "Passord",
        Database_Delete_Title_8: "JDBC-tilkoblingsstreng",
        Database_Rotate_Button: "Roter passord",
        Database_Delete_Desc_1: `Å slette en database er en permanent handling, og kan ikke angres. Dette vil permanent slette "{{database}}"-databasen og fjerne alle tilknyttede data.`,
        Database_Create_Desc_2: "Skriv inn databasenavnet for å bekrefte slettingen.",
        Database_Delete_Button: "Slett database",
        Database_Delete_Error_1: "Databasenavnet må oppgis.",
        Database_Delete_Error_2: "Databasevert ikke funnet: Vi fant ingen databaseverter som oppfyller kravene for denne serveren."
      },
      Server_Files: {
        Files_Page_Title: "Filbehandler",
        Files_Create_Button: "Ny Fil",
        Files_Directory_Empty: "Denne mappen ser ut til å være tom.",
        Files_Show_Files_Max: "Denne mappen er for stor til å vises i nettleseren din, noe som begrenser filene du ser til de første 250 filene.",
        Files_Chmod_Title: "Filmodus",
        Files_Chmod_Button: "Oppdater",
        Files_Delete_File_Or_Directory_Title: "Slett denne",
        Files_Delete_File_Or_Directory_Button: "Ja, slett",
        Files_Delete_File_Or_Directory_Desc: "Sletting av filer er en permanent operasjon, du kan ikke angre denne handlingen.",
        Files_Delete_File: "Fil",
        Files_Delete_Directory: "Mappe",
        Files_Delete_Title: "Vil du slette disse filene?",
        Files_Delete_Desc_1: "Er du sikker på at du vil slette disse filene {{selected}}?",
        Files_Delete_Desc_2: "Deleting the file(s) listed below is a permanent operation, you cannot undo this action.",
        Files_Delete_Desc_3: "andre",
        Files_Delete_Button: "Ja, slett filene",
        Files_SubMenu_Rename: "Gi nytt navn",
        Files_SubMenu_Move: "Flytt",
        Files_SubMenu_Permissions: "Tillatelser",
        Files_SubMenu_Copy: "Kopier",
        Files_SubMenu_Archive: "Arkiver",
        Files_SubMenu_Unarchive: "Pakk ut",
        Files_SubMenu_Download: "Last ned",
        Files_SubMenu_Delete: "Slett",
        Files_Edit_Ptero_Ignore_1: "You're editing a",
        Files_Edit_Ptero_Ignore_2: "file. Any files or directories listed in here will be excluded from backups. Wildcards are supported by using an asterisk",
        Files_Edit_Ptero_Ignore_3: "You can negate a prior rule by prepending an exclamation point",
        Files_Edit_Save_Button: "Lagre innhold",
        Files_Create_Title: "Filnavn",
        Files_Create_Desc: "Enter the name that this file should be saved as.",
        Files_Create_Error: "FileName is a required field",
        Files_Create_Button: "Opprett ny fil",
        Files_Message_Archiving: "Arkiverer filer...",
        Files_Message_Deleting: "Sletter filer...",
        Files_Create_Directory_Title: "Mappenavn",
        Files_Create_Directory_Desc_1: "A valid directory name must be provided.",
        Files_Create_Directory_Desc_2: "This directory will be created as",
        Files_Create_Directory_Button: "Create Directory",
        Files_Move_Desc_1: "Enter the new name and directory of this file or folder, relative to the current directory.",
        Files_Move_Desc_2: "Ny plassering:",
        Files_Drag_Desc: "Drag and drop files to upload.",
        Files_Drag_Button: "Last opp",
        Files_Error_1: "A name for the file is required.",
        Files_Error_2: "An error occurred on the remote host: Cannot move or rename file, destination already exists.."
      },
      Server_Users: {
        User_Page_Title: "Brukere",
        User_Sub_Users_Empty: "It looks like you don't have any subusers.",
        User_Create_Title_1: "Create new subuser",
        User_Create_Title_2: "User Email",
        User_Create_Sub_User_Desc_1: "Enter the email address of the user you wish to invite as a subuser for this server.",
        User_Create_Sub_User_Desc_2: "Email addresses must not exceed 191 characters.",
        User_Create_Sub_User_Desc_3: "A valid email address must be provided.",
        User_Modify_Or_View_Email_Title: "permissions for {{subuser}}",
        User_Modify_Title: "Modifiser",
        User_View_Title: "Vis",
        User_Modify_Button: "Lagre",
        User_Create_Button_1: "Inviter bruker",
        User_Create_Button_2: "Ny bruker",
        User_Create_Sub_User_Desc: "Only permissions which your account is currently assigned may be selected when creating or modifying other users.",
        User_Delete_Title: "Delete this subuser?",
        User_Delete_Desc_1: "Are you sure you wish to remove this subuser? They will have all access to this server revoked immediately.",
        User_Delete_Button: "Yes, remove subuser",
        User_Show_2FA: "2FA Aktivert",
        User_Show_Permissions: "Permissions",
        User_Create_Sub_Title_1: "Control",
        User_Create_Sub_Title_2: "User",
        User_Create_Sub_Title_3: "File",
        User_Create_Sub_Title_4: "Backup",
        User_Create_Sub_Title_5: "Allocation",
        User_Create_Sub_Title_6: "Startup",
        User_Create_Sub_Title_7: "Database",
        User_Create_Sub_Title_8: "Schedule",
        User_Create_Sub_Title_9: "Settings",
        User_Create_Desc_1: "Permissions that control a users ability to control the power state of a server, or send commands.",
        User_Create_Desc_2: "Permissions that allow a user to manage other subusers on a server. They will never be able to edit their own account, or assign permissions they do not have themselves.",
        User_Create_Desc_3: "Permissions that control a user's ability to modify the filesystem for this server.",
        User_Create_Desc_4: "Permissions that control a user's ability to generate and manage server backups.",
        User_Create_Desc_5: "Permissions that control a user's ability to modify the port allocations for this server.",
        User_Create_Desc_6: "Permissions that control a user's ability to view this server's startup parameters.",
        User_Create_Desc_7: "Permissions that control a user's access to the database management for this server.",
        User_Create_Desc_8: "Permissions that control a user's access to the schedule management for this server.",
        User_Create_Desc_9: "Permissions that control a user's access to the settings for this server.",
        User_Create_Option_Desc_1: "Konsoll",
        User_Create_Option_Desc_2: "Start",
        User_Create_Option_Desc_3: "Stopp",
        User_Create_Option_Desc_4: "Restart",
        User_Create_Option_Desc_5: "Opprett",
        User_Create_Option_Desc_6: "Lese",
        User_Create_Option_Desc_7: "Oppdatere",
        User_Create_Option_Desc_8: "Slette",
        User_Create_Option_Desc_9: "Lese innhold",
        User_Create_Option_Desc_10: "Arkiver",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Nedlastning",
        User_Create_Option_Desc_13: "Gjenoppretting",
        User_Create_Option_Desc_14: "Docker-image",
        User_Create_Option_Desc_15: "Vis passordet",
        User_Create_Option_Desc_16: "Gi nytt navn",
        User_Create_Option_Desc_17: "Installer på nytt",
        User_Create_Option_Description_1: "Allows a user to send commands to the server instance via the console.",
        User_Create_Option_Description_2: "Allows a user to start the server if it is stopped.",
        User_Create_Option_Description_3: "Allows a user to stop a server if it is running.",
        User_Create_Option_Description_4: "Allows a user to perform a server restart. This allows them to start the server if it is offline, but not put the server in a completely stopped state.",
        User_Create_Option_Description_5: "Allows a user to create new subusers for the server.",
        User_Create_Option_Description_6: "Allows the user to view subusers and their permissions for the server.",
        User_Create_Option_Description_7: "Allows a user to modify other subusers.",
        User_Create_Option_Description_8: "Allows a user to delete a subuser from the server.",
        User_Create_Option_Description_9: "Allows a user to create additional files and folders via the Panel or direct upload.",
        User_Create_Option_Description_10: "Allows a user to view the contents of a directory, but not view the contents of or download files.",
        User_Create_Option_Description_11: "Allows a user to view the contents of a given file. This will also allow the user to download files.",
        User_Create_Option_Description_12: "Allows a user to update the contents of an existing file or directory.",
        User_Create_Option_Description_13: "Allows a user to delete files or directories.",
        User_Create_Option_Description_14: "Allows a user to archive the contents of a directory as well as decompress existing archives on the system.",
        User_Create_Option_Description_15: "Allows a user to connect to SFTP and manage server files using the other assigned file permissions.",
        User_Create_Option_Description_16: "Allows a user to create new backups for this server.",
        User_Create_Option_Description_17: "Allows a user to view all backups that exist for this server.",
        User_Create_Option_Description_18: "Allows a user to remove backups from the system.",
        User_Create_Option_Description_19: "Allows a user to download a backup for the server. Danger: this allows a user to access all files for the server in the backup.",
        User_Create_Option_Description_20: "Allows a user to restore a backup for the server. Danger: this allows the user to delete all of the server files in the process.",
        User_Create_Option_Description_21: "Allows a user to view all allocations currently assigned to this server. Users with any level of access to this server can always view the primary allocation.",
        User_Create_Option_Description_22: "Allows a user to assign additional allocations to the server.",
        User_Create_Option_Description_23: "Allows a user to change the primary server allocation and attach notes to each allocation.",
        User_Create_Option_Description_24: "Allows a user to delete an allocation from the server.",
        User_Create_Option_Description_25: "Allows a user to view the startup variables for a server.",
        User_Create_Option_Description_26: "Allows a user to modify the startup variables for the server.",
        User_Create_Option_Description_27: "Allows a user to modify the Docker image used when running the server.",
        User_Create_Option_Description_28: "Allows a user to create a new database for this server.",
        User_Create_Option_Description_29: "Allows a user to view the database associated with this server.",
        User_Create_Option_Description_30: "Allows a user to rotate the password on a database instance. If the user does not have the view_password permission they will not see the updated password.",
        User_Create_Option_Description_31: "Allows a user to remove a database instance from this server.",
        User_Create_Option_Description_32: "Allows a user to view the password associated with a database instance for this server.",
        User_Create_Option_Description_33: "Allows a user to create new schedules for this server.",
        User_Create_Option_Description_34: "Allows a user to view schedules and the tasks associated with them for this server.",
        User_Create_Option_Description_35: "Allows a user to update schedules and schedule tasks for this server.",
        User_Create_Option_Description_36: "Allows a user to delete schedules for this server.",
        User_Create_Option_Description_37: "Allows a user to rename this server.",
        User_Create_Option_Description_38: "Allows a user to trigger a reinstall of this server."
      },
      Server_Network: {
        Network_Page_Title: "Network",
        Network_Alocations_Desc_1: "You are currently using {{data}} of {{limit}} allowed allocations for this server.",
        Network_Create_Alocation_Button: "Create Allocation",
        Network_Hostname: "Hostname",
        Network_IP_Address: "IP Address",
        Network_Port: "Port",
        Network_Notes: "Notes",
        Network_Primary: "Primary",
        Network_Primary_Button: "Make Primary",
        Network_Delete_Title: "Remove this allocation?",
        Network_Delete_Button: "Delete",
        Network_Delete_Desc_1: "This allocation will be immediately removed from your server. Are you sure you want to continue?",
        Network_Error_1: "Server auto-allocation is not enabled for this instance.",
      },
      Server_Schedules: {
        Task_Page_Title: "Schedules",
        Task_Empty_Message: "There are no schedules configured for this server.",
        Task_Create_Button: "Create schedule",
        Task_Edit_Button: "Save changes",
        Task_Delete_Title: "Delete schedule?",
        Task_Delete_Button_1: "Yes, delete schedule",
        Task_Delete_Desc: "Are you sure you want to delete this schedule? All tasks will be removed and any running processes will be terminated.",
        Task_Delete_Button_2: "Delete",
        Task_Create_Title: "Create new schedule",
        Task_Edit_Title: "Edit schedule",
        Task_Create_Or_Edit_Title_1: "Schedule name",
        Task_Create_Or_Edit_Title_2: "Only When Server Is Online",
        Task_Create_Or_Edit_Title_3: "Schedule Enabled",
        Task_Create_Or_Edit_Desc_1: "A human readable identifer for this schedule.",
        Task_Create_Or_Edit_Desc_2: "The schedule system supports the use of Cronjob syntax when defining when tasks should begin running. Use the fields above to specify when these tasks should begin running.",
        Task_Create_Or_Edit_Desc_3: "Only execute this schedule when the server is in a running state.",
        Task_Create_Or_Edit_Desc_4: "This schedule will be executed automatically if enabled.",
        Task_Create_Or_Edit_Minute: "Minute",
        Task_Create_Or_Edit_Hour: "Hour",
        Task_Create_Or_Edit_Day_Of_Month: "Day of month",
        Task_Create_Or_Edit_Month: "Month",
        Task_Create_Or_Edit_Day_Of_Week: "Day of week",
        Task_New_Task_Button: "New Task",
        Task_Run_Task_Button: "Run Now",
        Task_Cron_Row_Minute: "Minute",
        Task_Cron_Row_Hour: "Hour",
        Task_Cron_Row_Day_Month: "Day (Month)",
        Task_Cron_Row_Month: "Month",
        Task_Cron_Row_Day_Week: "Day (Week)",
        Task_Task_Page_Title: "Tasks",
        Task_Task_Processing: "Processing",
        Task_Task_Last_Run: "Last run at:",
        Task_Task_Next_Run: "Next run at:",
        Task_Task_Never: "Never",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Edit",
        Task_Task_Active: "Active",
        Task_Task_Inactive: "Inactive",
        Task_Task_Delete_Title: "Confirm task deletion",
        Task_Task_Delete_Button: "Delete Task",
        Task_Task_Delete_Desc: "Are you sure you want to delete this task? This action cannot be undone.",
        Task_Task_Files_And_Folders_Message: "Ignoring files & folders:",
        Task_Task_Continue_Message: "Continues on Failure",
        Task_Task_Time_Message: "{{time}}s later",
        Task_Task_Edit_Title: "Edit Task",
        Task_Task_Create_Title: "Create Task",
        Task_Task_Create_Or_Edit_Command: "Send command",
        Task_Task_Create_Or_Edit_Power: "Send power action",
        Task_Task_Create_Or_Edit_Backup: "Create backup",
        Task_Task_Create_Or_Edit_Title_1: "Time offset (in seconds)",
        Task_Task_Create_Or_Edit_Title_2: "Payload",
        Task_Task_Create_Or_Edit_Title_3: "Ignored Files",
        Task_Task_Create_Or_Edit_Title_4: "Continue on Failure",
        Task_Task_Create_Or_Edit_Title_5: "Action",
        Task_Task_Create_Or_Edit_Desc_1: "The amount of time to wait after the previous task executes before running this one. If this is the first task on a schedule this will not be applied.",
        Task_Task_Create_Or_Edit_Desc_2: "Optional. Include the files and folders to be excluded in this backup. By default, the contents of your .pteroignore file will be used. If you have reached your backup limit, the oldest backup will be rotated.",
        Task_Task_Create_Or_Edit_Desc_3: "Future tasks will be run when this task fails.",
        Task_Task_Create_Or_Edit_Option_1: "Start the server",
        Task_Task_Create_Or_Edit_Option_2: "Restart the server",
        Task_Task_Create_Or_Edit_Option_3: "Stop the server",
        Task_Task_Create_Or_Edit_Option_4: "Terminate the server",
        Task_Task_Create_Or_Edit_Error_1: "A task payload must be provided.",
        Task_Task_Create_Or_Edit_Error_2: "The time offset must be a valid number between 0 and 900.",
        Task_Task_Create_Or_Edit_Error_3: "A time offset value must be provided.",
        Task_Task_Create_Or_Edit_Error_4: "The time offset must be at least 0 seconds.",
        Task_Task_Create_Or_Edit_Error_5: "The time offset must be less than 900 seconds.",
        Task_Task_Create_Or_Edit_Error_6: "A backup task cannot be created when the server's backup limit is set to 0."
      },
      Server_Settings: {
        Settings_Page_Title: "Innstillinger",
        Settings_SFTP_Title_1: "SFTP-Detaljer",
        Settings_SFTP_Title_2: "Server Address",
        Settings_SFTP_Title_3: "Brukernavn",
        Settings_SFTP_Desc_1: "Your SFTP password is the same as the password you use to access this panel.",
        Settings_SFTP_Button: "Kjør SFTP",
        Settings_Debug_Title_1: "Debug Information",
        Settings_Debug_Title_2: "Node",
        Settings_Debug_Title_3: "Server-ID",
        Settings_Reinstall_Title_1: "Reinstall Server",
        Settings_Reinstall_Title_2: "Confirm server reinstallation",
        Settings_Reinstall_Button: "Yes, reinstall server",
        Settings_Reinstall_Desc_1: "Your server will be stopped and some files may be deleted or modified during this process, are you sure you wish to continue?",
        Settings_Reinstall_Desc_2: "Reinstalling your server will stop it, and then re-run the installation script that initially set it up.",
        Settings_Reinstall_Desc_3: "Some files may be deleted or modified during this process, please back up your data before continuing.",
        Settings_Reinstall_Success: "Your server has begun the reinstallation process.",
        Settings_Reinstall_Error: "Could not establish a connection to the machine running this server. Please try again.",
        Settings_Rename_Server_Title_1: "Bytt servernavn",
        Settings_Rename_Server_Title_2: "Servernavn",
        Settings_Rename_Server_Button: "Lagre",
        Settings_Rename_Required: "Navn er et obligatorisk felt"
      },
      Server_Startup: {
        Startup_Page_Title: "Startup Settings",
        Startup_Command_Title_1: "Startup Command",
        Startup_Docker_Title: "Docker Image",
        Startup_Docker_Desc: "This is an advanced feature allowing you to select a Docker image to use when running this server instance.",
        Startup_Docker_Error: "This server's Docker image has been manually set by an administrator and cannot be changed through this UI.",
        Startup_Variables_Title: "Variables",
        Startup_Variables_Read: "Read Only",
        Startup_Server_Error_Title: "Oops!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Invalid Java version, update Docker image?",
        Features_Invalid_Java_Desc_1: "This server is unable to start due to the required Java version not being met.",
        Features_Invalid_Java_Desc_2: `By pressing "Update Docker Image" below you are acknowledging that the Docker image this server uses will be changed to an image below that has the Java version you are requesting.`,
        Features_Invalid_Java_Desc_3: "Please select a Java version from the list below.",
        Features_Invalid_Java_Button_1: "Update Docker Image",
        Features_Invalid_Java_Button_2: "Avbryt",
        Features_Accept_Eula_Title: "Accept Minecraft® EULA",
        Features_Accept_Eula_Desc_1: `By pressing "I Accept" below you are indicating your agreement to the`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Jeg godtar",
        Features_Accept_Eula_Button_2: "Avbryt",
        Features_Invalid_GSL_Title: "Invalid GSL token!",
        Features_Invalid_GSL_Desc_1: "It seems like your Gameserver Login Token (GSL token) is invalid or has expired.",
        Features_Invalid_GSL_Desc_2: "You can either generate a new one and enter it below or leave the field blank to remove it completely.",
        Features_Invalid_GSL_Desc_3: "GSL Token",
        Features_Invalid_GSL_Desc_4: "Visit https://steamcommunity.com/dev/managegameservers to generate a token.",
        Features_Invalid_GSL_Button: "Update GSL Token",
        Features_Invalid_PID_Title_1: "Memory or process limit reached...",
        Features_Invalid_PID_Title_2: "Possible resource limit reached...",
        Features_Invalid_PID_Desc_1: "This server has reached the maximum process or memory limit.",
        Features_Invalid_PID_Desc_2: "Increasing",
        Features_Invalid_PID_Desc_3: "container_pid_limit",
        Features_Invalid_PID_Desc_4: "in the wings configuration,",
        Features_Invalid_PID_Desc_5: "config.yml",
        Features_Invalid_PID_Desc_6: ", might help resolve this issue.",
        Features_Invalid_PID_Desc_7: "Note: Wings must be restarted for the configuration file changes to take effect",
        Features_Invalid_PID_Desc_8: "This server is attempting to use more resources than allocated. Please contact the administrator and give them the error below.",
        Features_Invalid_PID_Desc_9: "pthread_create failed, Possibly out of memory or process/resource limits reached",
        Features_Invalid_Disk_Title: "Out of available disk space...",
        Features_Invalid_Disk_Desc_1: "This server has run out of available disk space and cannot complete the install or update process.",
        Features_Invalid_Disk_Desc_2: "Ensure the machine has enough disk space by typing",
        Features_Invalid_Disk_Desc_3: "df -h",
        Features_Invalid_Disk_Desc_4: "on the machine hosting this server. Delete files or increase the available disk space to resolve the issue.",
        Features_Invalid_Disk_Desc_5: "This server has run out of available disk space and cannot complete the install or update process. Please get in touch with the administrator(s) and inform them of disk space issues.",
      },
      Server_States: {
        Server_Installing_Title: "Running Installer",
        Server_Installing_Desc: "Your server should be ready soon, please try again in a few minutes.",
        Server_Suspended_Title: "Server Suspended",
        Server_Suspended_Desc: "This server is suspended and cannot be accessed.",
        Server_Transferring_Title: "Transferring",
        Server_Transferring_Desc: "Your server is being transfered to a new node, please check back later.",
        Server_Restoring_Title: "Restoring from Backup",
        Server_Restoring_Desc: "Your server is currently being restored from a backup, please check back in a few minutes."
      },
      Page_Titles: {
        Title_Console: "Konsoll",
        Title_File_Manager: "Filbehandler",
        Title_Databases: "Databaser",
        Title_Schedules: "Tidsplaner",
        Title_Users: "Brukere",
        Title_Backups: "Sikkerhetskopier",
        Title_Network: "Nettverk",
        Title_Startup: "Oppstart",
        Title_Settings: "Innstillinger",
        Title_API_Credentials: "API Credentials"
      },
      Errors: {
        Error_Key_Undefined: "Internal Error: The key for this message has not been set, contact the author: Ferks#7575",
        Error_Server_Title: "Noe gikk galt",
        Error_Server_Desc: "The requested resource was not found.",
        Error_Connection: "There was an error while communicating with the machine running this server. This error has been logged, please try again.",
        Error_Network: "Nettverksfeil",
        Error_Permission_Title: "Ingen tilgang",
        Error_Permission_Desc: "You do not have permission to access this page.",
        Error_Variables_1: "The value field is required.",
        Error_Variables_2: "The value must be 1 digits.",
        Error_Variables_3: "This value is not valid.",
        Error_Variables_4: "The value must be at least 1.",
        Error_Variables_5: "This value is greater than the limit.",
        Error_Variables_6: "The value format is invalid.",
        Error_Variables_7: "The value may only contain letters, numbers, and dashes."
      },
      System_Translation: {
        System_Change_Language_Title: "Configure Language",
        System_Change_Language_Desc: "Choose a language to be rendered in your panel."
      }
    }
}
